#
#
#

default: &default
  adapter: postgresql
  encoding: unicode 
  host: localhost
  pool: 5
  port: 5432
  username: eris
  hosts:
        - 127.0.0.1:5432

development:
  <<: *default
  database: todo_development
  password: 'youmustdestroyit'

 
test:
  <<: *default
  database: todo_test
  password: 'youmustdestroyit'

production:
  <<: *default
  database: todo_production
  username: eris
  password: 'youmustdestroyit'

  #
  #
  #